//! Generates the derivable pages of the Entity Runtime documentation site, checks them for drift,
//! and binds a built site to its source commit. The site build itself is Docusaurus.
//!
//! `generate` writes four files:
//!
//! - `website/docs/reference/cli.md`, walked from [`entity_cli::cli::Cli`];
//! - `website/docs/reference/crates.md`, from `cargo metadata --no-deps`;
//! - `website/data/status.json` (`b10x-status/1`) and `website/docs/status.md`, from
//!   [`status::CAPABILITIES`], where every shipped item names the test that holds it and generation
//!   fails when that test is gone.
//!
//! `generate --check` writes nothing and fails on a stale or hand-edited file. Both also check every
//! page (`pages`, `kinds`): front matter, bracketed admonition titles, the passive Markdown the
//! unified documentation site accepts, code blocks titled with a repository file, and that the
//! typed refusals page names every refusal kind the code returns.
//!
//! `provenance` writes `.well-known/b10x-site.json` and the route inventory
//! `.well-known/b10x-routes.json` into a built site.

mod cli;
mod crates;
mod kinds;
mod pages;
mod routes;
mod status;

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::ExitCode,
};

use clap::{Parser, Subcommand};

/// Every failure is reported as one message and exit code 1.
type Result<T> = std::result::Result<T, String>;

/// The first line of every generated page's front matter.
const FRONT_MATTER_HEADER: &str = "# generated by entity-runtime-docs, do not edit";
/// A file in the repository on GitHub, by path.
const SOURCE: &str = "https://github.com/beyond10x/entity-runtime/blob/main";
/// A directory in the repository on GitHub, by path.
const TREE: &str = "https://github.com/beyond10x/entity-runtime/tree/main";
/// Every documentation page, relative to the repository root.
const DOCS: &str = "website/docs";

#[derive(Parser)]
#[command(about = "Generate and check the derived pages of the Entity Runtime documentation site")]
struct Cli {
    #[command(subcommand)]
    command: Action,
}

#[derive(Subcommand)]
enum Action {
    /// Regenerate the reference pages and the status page and data, or check them for drift.
    Generate {
        /// Write nothing; fail when a generated file is missing, stale or hand-edited.
        #[arg(long)]
        check: bool,
        /// Repository root.
        #[arg(long, default_value = ".")]
        root: PathBuf,
    },
    /// Bind a built site to its source commit: write `.well-known/b10x-site.json` and the route
    /// inventory `.well-known/b10x-routes.json` into it.
    Provenance {
        /// The built site, `website/build`.
        #[arg(long)]
        site: PathBuf,
        /// The full Git revision the site was built from.
        #[arg(long)]
        commit: String,
    },
}

/// Generated files keyed by their path relative to the repository root.
type Outputs = BTreeMap<&'static str, String>;

fn outputs(root: &Path) -> Result<Outputs> {
    Ok(Outputs::from([
        (cli::PAGE, cli::page(root)?),
        (crates::PAGE, crates::page(root)?),
        (status::DATA, status::data(root)?),
        (status::PAGE, status::page(root)?),
    ]))
}

/// The drift of one generated file: `None` when it is current.
fn drift(root: &Path, relative: &str, expected: &str) -> Option<String> {
    match fs::read_to_string(root.join(relative)) {
        Err(_) => Some(format!("missing {relative}")),
        Ok(found) if found != expected => Some(format!("stale or edited {relative}")),
        Ok(_) => None,
    }
}

fn generate(root: &Path, check: bool) -> Result<()> {
    let outputs = outputs(root)?;
    if check {
        let problems: Vec<_> = outputs
            .iter()
            .filter_map(|(relative, content)| drift(root, relative, content))
            .collect();
        if !problems.is_empty() {
            return Err(format!(
                "generated files have drifted ({}); run `task docs-generate`",
                problems.join(", ")
            ));
        }
        for relative in outputs.keys() {
            println!("{relative}: current");
        }
    } else {
        for (relative, content) in &outputs {
            let path = root.join(relative);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|error| format!("creating {}: {error}", parent.display()))?;
            }
            fs::write(&path, content).map_err(|error| format!("writing {relative}: {error}"))?;
            println!("{relative}: written");
        }
    }
    let problems = pages::check(root)?;
    if !problems.is_empty() {
        return Err(format!(
            "documentation pages fail their checks:\n  {}",
            problems.join("\n  ")
        ));
    }
    println!(
        "{DOCS}: front matter, admonition titles, passive Markdown, titled code blocks and refusal kinds checked"
    );
    Ok(())
}

/// The project-site publication record for one build of the `/entity-runtime/` site.
fn site_manifest(commit: &str) -> Result<String> {
    if commit.len() != 40
        || !commit.bytes().all(|b| b.is_ascii_hexdigit())
        || commit.bytes().all(|b| b == b'0')
    {
        return Err("commit must be a nonzero full Git revision".to_owned());
    }
    Ok(format!(
        "{{\n  \"baseUrl\": \"{}\",\n  \"commit\": \"{commit}\",\n  \"repository\": \"entity-runtime\",\n  \"schema\": \"b10x-project-site/v1\"\n}}",
        routes::BASE
    ))
}

fn write_provenance(site: &Path, commit: &str) -> Result<()> {
    let manifest = site_manifest(commit)?;
    if !site.join("index.html").is_file() {
        return Err(format!("{} holds no built site", site.display()));
    }
    let write = |path: PathBuf, content: &str| {
        fs::write(&path, content).map_err(|error| format!("writing {}: {error}", path.display()))
    };
    fs::create_dir_all(site.join(".well-known"))
        .map_err(|error| format!("creating .well-known: {error}"))?;
    let inventory = routes::inventory(site, commit)?;
    write(site.join(".well-known/b10x-site.json"), &manifest)?;
    write(site.join(".well-known/b10x-routes.json"), &inventory)?;
    write(site.join(".nojekyll"), "")
}

fn main() -> ExitCode {
    let result = match Cli::parse().command {
        Action::Generate { check, root } => generate(&root, check),
        Action::Provenance { site, commit } => write_provenance(&site, &commit)
            .map(|()| println!("{}: bound to {commit}", site.display())),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("entity-runtime-docs: {message}");
            ExitCode::FAILURE
        }
    }
}

/// Quote a value as a YAML double-quoted scalar.
fn yaml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

/// `value` as one Markdown table cell: on one line, with `|` escaped.
fn cell(value: &str) -> String {
    value
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('|', "\\|")
}

/// The front matter of a generated page: the generator line, title, label, sidebar position,
/// description and no edit link.
fn front_matter(title: &str, label: &str, description: &str, position: u32) -> String {
    format!(
        "---\n{FRONT_MATTER_HEADER}\ntitle: {}\nsidebar_label: {}\nsidebar_position: {position}\ndescription: {}\ncustom_edit_url: null\n---\n\n",
        yaml_string(title),
        yaml_string(label),
        yaml_string(description),
    )
}

/// The repository root, for tests.
#[cfg(test)]
fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// A fresh scratch directory under the system temporary directory, for tests.
#[cfg(test)]
fn scratch(name: &str) -> PathBuf {
    let dir =
        std::env::temp_dir().join(format!("entity-runtime-docs-{name}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("scratch directory");
    dir
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn provenance_refuses_anything_but_a_full_nonzero_revision() {
        let commit = "e86f43d90b637fc2c1790f77d59efff2eb852386";
        let manifest = site_manifest(commit).unwrap();
        assert!(manifest.contains(&format!("\"commit\": \"{commit}\"")));
        assert!(manifest.contains("\"baseUrl\": \"/entity-runtime/\""));
        assert!(manifest.contains("\"schema\": \"b10x-project-site/v1\""));
        for bad in [
            "e86f43d",
            &"0".repeat(40),
            &format!("{}\"", &commit[..39]),
            &format!("{commit}0"),
        ] {
            assert!(site_manifest(bad).is_err(), "{bad}");
        }
    }

    #[test]
    fn provenance_writes_both_documents_into_a_built_site_only() {
        let commit = "e86f43d90b637fc2c1790f77d59efff2eb852386";
        let site = scratch("provenance");
        assert!(write_provenance(&site, commit).is_err());
        fs::write(site.join("index.html"), r#"<main id="main">"#).unwrap();
        write_provenance(&site, commit).unwrap();
        let manifest = fs::read_to_string(site.join(".well-known/b10x-site.json")).unwrap();
        assert_eq!(manifest, site_manifest(commit).unwrap());
        let routes = fs::read_to_string(site.join(".well-known/b10x-routes.json")).unwrap();
        assert!(routes.contains("\"path\": \"/entity-runtime/\""));
        assert!(site.join(".nojekyll").is_file());
        fs::remove_dir_all(site).unwrap();
    }

    #[test]
    fn yaml_strings_escape_quotes_and_backslashes() {
        assert_eq!(yaml_string(r#"a "b" \c"#), r#""a \"b\" \\c""#);
    }

    #[test]
    fn every_generated_file_is_current_in_this_tree() {
        let root = repository_root();
        for (relative, content) in outputs(&root).unwrap() {
            let found = fs::read_to_string(root.join(relative))
                .unwrap_or_else(|_| panic!("{relative} is missing; run `task docs-generate`"));
            assert!(
                found == content,
                "{relative} is stale; run `task docs-generate`"
            );
        }
    }

    #[test]
    fn every_documentation_page_passes_its_checks() {
        let problems = pages::check(&repository_root()).unwrap();
        assert!(problems.is_empty(), "{problems:#?}");
    }
}
