//! Release probes for shared-batch closure growth and open cost on real SQLite authority.
//!
//! Run explicitly with `cargo +1.91.0 test --release -p entity-eventlog
//! --features sqlite,sync-bridge --test shared_clock_cost -- --ignored --nocapture`.
//! Seeding uses public kernel/canonical-byte/provider APIs and the real ER projector;
//! a complete cold open validates the fixture before any measurement.
#![cfg(all(feature = "sqlite", feature = "sync-bridge"))]

use entity_core::{Registry, Runtime};
use entity_eventlog::{
    AsyncBindingProvisioner, Authority, CapturePolicy, ErRecordedProjector,
    EventlogBindingProvisioner, EventlogOperationContext, EventlogRecordedStore, OpenVerification,
    RecordedProviderFacade, projection_specs,
    sync::{BridgeConfig, CallWait, EventlogRecordedStoreOwner, ShutdownMode, ShutdownOutcome},
};
use entity_executor::{BatchAction, CreateRequest, ExecuteRequest};
use entity_store::{
    Expect, RecordedCommit, Recording,
    asynchronous::{
        AppendMember, AsyncRecordedReader, BatchKey, RecordedEntry, Subject,
        batch_comparison_bytes, canonical_domain_bytes, original_request_comparison_bytes,
        read_record_in_domain, record_comparison_bytes, record_domain,
    },
};
use eventlog_core::{
    AppendGroup, AtomicEventStore, CaptureLimits, CommandMeta, ConsistentTenantCapture, EventStore,
    Expected, InlineProjectionAdmin, NewEvent, NoGuard, StreamAppend, StreamId, TenantId,
};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    num::NonZeroU16,
    path::Path,
    sync::Arc,
    time::{Duration, Instant},
};
use time::OffsetDateTime;

const PREFIX: &str = "shared_clock_cost";
const LIMITS: CaptureLimits = CaptureLimits {
    max_events: 10_000,
    max_blobs: 40_000,
    max_projection_rows: 40_000,
    max_payload_bytes: 512 * 1024 * 1024,
};

fn registry() -> Registry {
    let mut fields = serde_json::Map::new();
    fields.insert("title".into(), json!({"type":"string", "required":true}));
    for index in 0..96 {
        fields.insert(
            format!("metadata_field_{index:04}_carrying_a_long_declared_name"),
            json!({"type":"string", "max_length":64}),
        );
    }
    let mut registry = Registry::new();
    registry
        .register(
            serde_json::from_value(json!({
                "entity":"metadata", "version":1, "schema":{"fields":fields},
                "lifecycle":{"initial":"open", "states":["open"]},
                "operations":{"touch":{"transitions":[{"from":"open", "to":"open"}], "emits":[]}}
            }))
            .unwrap(),
        )
        .unwrap();
    registry
}

fn recording(id: &str) -> Recording {
    Recording {
        record_id: id.into(),
        recorded_at: "2026-10-03T00:00:00Z".into(),
        correlation: None,
        causation: None,
        actor: None,
    }
}
fn context(id: &str) -> EventlogOperationContext {
    EventlogOperationContext {
        subject: "cost-probe".into(),
        actor: "entity-eventlog-test".into(),
        request_id: format!("request-{id}"),
        trace_id: format!("trace-{id}"),
        causation_id: None,
        causation_depth: 0,
        occurred_at: OffsetDateTime::UNIX_EPOCH,
    }
}
fn framed(domain: &str, bytes: &[u8]) -> String {
    let mut hash = Sha256::new();
    hash.update(domain.as_bytes());
    hash.update([0]);
    hash.update((bytes.len() as u64).to_be_bytes());
    hash.update(bytes);
    format!("sha256:{:x}", hash.finalize())
}
fn key(domain: &str, value: Value) -> String {
    let wrapped = canonical_domain_bytes("_", value).unwrap();
    framed(domain, &wrapped[5..wrapped.len() - 1])
}

// Fixture wire envelopes intentionally live only in this test. Real projector and cold ER
// verification must accept every generated byte; measured operations use no fixture shortcut.
async fn seed_group(
    backend: &eventlog_sqlite::SqliteEventStore,
    authority: &Authority,
    index: usize,
    members: Vec<AppendMember>,
) {
    let batch_key = BatchKey::Named(format!("seed-{index}"));
    let batch_wire = json!(["named", format!("seed-{index}")]);
    let batch_bytes = batch_comparison_bytes(&batch_key, &members).unwrap();
    let batch_digest = framed("er.eventlog.batch-blob-key/1", &batch_bytes);
    let mut blobs = vec![(batch_digest.clone(), batch_bytes)];
    let tenant = TenantId::new(&authority.tenant).unwrap();
    let mut appends = Vec::new();
    for (member_index, member) in members.iter().enumerate() {
        let subject = member.entry.subject();
        let record_bytes = record_comparison_bytes(&member.entry).unwrap();
        let record_digest = framed("er.eventlog.record-blob-key/1", &record_bytes);
        let request_digest = framed("er.eventlog.request-blob-key/1", &member.request_bytes);
        let wrapper = canonical_domain_bytes(
            "er.eventlog.recorded-entry/1",
            json!({
                "authority":authority, "batch_blob":batch_digest, "batch_key":batch_wire,
                "member_index":member_index, "record_blob":record_digest,
                "request_blob":request_digest, "subject":[subject.entity, subject.id],
            }),
        )
        .unwrap();
        let wrapper_digest = framed("er.eventlog.recorded-entry-blob-key/1", &wrapper);
        blobs.extend([
            (record_digest, record_bytes),
            (request_digest, member.request_bytes.clone()),
            (wrapper_digest.clone(), wrapper),
        ]);
        let stream_key = key(
            "er.eventlog.subject-stream-key/1",
            json!({"authority":authority, "subject":[subject.entity, subject.id]}),
        );
        appends.push(StreamAppend {
            stream: StreamId::new(tenant.clone(), "er.subject", stream_key).unwrap(),
            expected: match member.expect {
                Expect::Absent => Expected::NoStream,
                Expect::Revision(revision) => Expected::Exact(revision),
            },
            events: vec![
                NewEvent::new("er.recorded_entry", 1, json!({"blob":wrapper_digest})).unwrap(),
            ],
        });
    }
    let ctx = context(&format!("seed-{index}"));
    let group = AppendGroup {
        tenant,
        appends,
        meta: CommandMeta {
            idempotency_key: key(
                "er.eventlog.batch-command-key/1",
                json!({"authority":authority,"batch_key":batch_wire}),
            ),
            request_hash: batch_digest,
            subject: ctx.subject,
            actor: ctx.actor,
            request_id: ctx.request_id,
            trace_id: ctx.trace_id,
            causation_id: None,
            causation_depth: 0,
            occurred_at: ctx.occurred_at,
            claim: None,
        },
    };
    let result = backend
        .append_group_guarded_with_blobs(&group, Arc::new(NoGuard), &blobs)
        .await
        .expect("fixture group/projector commits");
    assert!(!result.deduplicated);
    assert_eq!(result.appends.len(), 2);
}

async fn seeded(path: &Path, registry: &Registry, total_events: usize) -> (Authority, u64) {
    assert_eq!(total_events % 2, 1);
    let backend = Arc::new(
        eventlog_sqlite::SqliteEventStore::open(path.to_str().unwrap(), PREFIX)
            .await
            .unwrap(),
    );
    let tenant = TenantId::new("shared-clock").unwrap();
    let authority = Authority {
        logical_scope: "shared-clock-scope".into(),
        tenant: tenant.as_str().into(),
        stream_identity: backend.stream_identity(&tenant).await.unwrap(),
    };
    let projector = Arc::new(ErRecordedProjector::new());
    backend.create_projections(projector.clone()).await.unwrap();
    backend.attach_inline_existing(projector).await.unwrap();
    EventlogBindingProvisioner::new(backend.clone(), LIMITS)
        .provision_binding(authority.clone(), context("binding"))
        .await
        .unwrap();
    let runtime = Runtime::new(registry);
    let mut clock = None;
    let groups = (total_events - 1) / 2;
    for index in 0..groups {
        let decision = match clock.as_ref() {
            None => runtime.create("metadata", 1, "clock", json!({"title":"clock"})),
            Some(instance) => runtime.execute(instance, "touch", json!({})),
        }
        .unwrap();
        let expected = clock
            .as_ref()
            .map_or(Expect::Absent, |state: &entity_core::EntityInstance| {
                Expect::Revision(state.revision)
            });
        clock = Some(decision.instance.clone());
        let clock_entry = RecordedEntry::Decision(
            RecordedCommit::new(decision, &recording(&format!("clock-{index}"))).unwrap(),
        );
        let peer_id = format!("peer-{index}");
        let peer_entry = RecordedEntry::Decision(
            RecordedCommit::new(
                runtime
                    .create("metadata", 1, &peer_id, json!({"title":peer_id}))
                    .unwrap(),
                &recording(&format!("peer-{index}")),
            )
            .unwrap(),
        );
        let members = [(clock_entry, expected), (peer_entry, Expect::Absent)]
            .into_iter()
            .map(|(entry, expect)| {
                let bytes = original_request_comparison_bytes(&entry).unwrap();
                AppendMember::new(expect, entry, bytes)
            })
            .collect();
        seed_group(&backend, &authority, index, members).await;
    }
    let capture = backend
        .capture_tenant(&tenant, projection_specs(), LIMITS)
        .await
        .unwrap();
    assert_eq!(
        capture.events.len(),
        total_events,
        "includes one authority-binding event"
    );
    println!(
        "seed events={total_events} recorded_entries={} groups={groups} blob_bytes={}",
        total_events - 1,
        capture
            .blobs
            .iter()
            .map(|blob| blob.bytes.len())
            .sum::<usize>()
    );
    drop(capture);
    let verified = EventlogRecordedStore::open_with_policy(
        backend,
        authority.clone(),
        LIMITS,
        CapturePolicy::ProviderTracked,
    )
    .await
    .expect("cold ER verification validates all fixture bytes and histories");
    // Counted before any read: a later complete read takes a capture of its own when the open took
    // none, so a count taken after it cannot tell an open that verified from one that did not.
    let opened = verified.calls();
    assert_eq!(
        (opened.captures, opened.model_builds),
        (1, 1),
        "cold open remains fully verified: {opened:?}"
    );
    let snapshot = verified
        .complete_snapshot(&authority.logical_scope)
        .await
        .unwrap();
    assert_eq!(
        snapshot
            .histories
            .iter()
            .map(|h| h.history.records.len())
            .sum::<usize>(),
        total_events - 1
    );
    assert_eq!(snapshot.histories.len(), groups + 1);
    let before = verified.calls();
    let start = Instant::now();
    let unchanged = verified
        .complete_snapshot(&authority.logical_scope)
        .await
        .unwrap();
    let unchanged_time = start.elapsed();
    assert_eq!(unchanged, snapshot);
    assert_eq!(
        before.captures, 1,
        "the first complete read reuses the open's verification"
    );
    assert_eq!(
        verified.calls(),
        before,
        "unchanged capture does no new verification work"
    );
    println!(
        "unchanged events={total_events} elapsed={unchanged_time:?} calls_before={before:?} calls_after={:?}",
        verified.calls()
    );
    (authority, groups as u64)
}

/// Opens the seeded store the way a short-lived consumer process does: one owner, its own worker.
fn start_tracked(path: &Path, registry: &Registry, authority: Authority) -> RecordedProviderFacade {
    RecordedProviderFacade::start_with_read_policy(
        registry.clone(),
        EventlogRecordedStoreOwner::Sqlite {
            path: path.to_string_lossy().into_owned(),
            prefix: PREFIX.into(),
            authority,
            limits: LIMITS,
        },
        BridgeConfig {
            queue_capacity: NonZeroU16::new(8).unwrap(),
        },
        CapturePolicy::ProviderTracked,
    )
    .unwrap()
}

/// A provider handle opened on the seeded file with the projector attached, as an owner opens it.
fn attached(
    runtime: &tokio::runtime::Runtime,
    path: &Path,
) -> Arc<eventlog_sqlite::SqliteEventStore> {
    runtime.block_on(async {
        let backend = Arc::new(
            eventlog_sqlite::SqliteEventStore::open_existing(path.to_str().unwrap(), PREFIX)
                .await
                .unwrap(),
        );
        backend
            .attach_inline_existing(Arc::new(ErRecordedProjector::new()))
            .await
            .unwrap();
        backend
    })
}

fn micros(samples: &[Duration]) -> String {
    let listed: Vec<String> = samples.iter().map(|d| d.as_micros().to_string()).collect();
    listed.join(",")
}

fn median(samples: &mut [Duration]) -> Duration {
    samples.sort();
    samples[samples.len() / 2]
}
fn measured<T>(f: impl FnOnce() -> T) -> (T, Duration) {
    let start = Instant::now();
    let output = f();
    (output, start.elapsed())
}

#[test]
#[ignore = "release performance probe; run explicitly on a quiet host"]
fn warm_shared_clock_batches_remain_within_twice_small_store_cost() {
    assert!(!cfg!(debug_assertions), "this probe requires --release");
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target/issue-51-scratch/perf");
    std::fs::create_dir_all(&root).unwrap();
    let directory = tempfile::tempdir_in(root).unwrap();
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();
    let registry = registry();
    let mut batch_medians = Vec::new();
    for count in [55, 601, 1203] {
        let path = directory.path().join(format!("events-{count}.sqlite3"));
        let seed_start = Instant::now();
        let (authority, mut revision) = runtime.block_on(seeded(&path, &registry, count));
        println!(
            "seed_and_verify events={count} elapsed={:?}",
            seed_start.elapsed()
        );
        let (mut facade, open_elapsed) = measured(|| start_tracked(&path, &registry, authority));
        let clock = Subject::new("metadata", "clock").unwrap();
        let mut batches = Vec::new();
        let mut histories = Vec::new();
        let mut lookups = Vec::new();
        let mut snapshots = Vec::new();
        for sample in 0..6 {
            let label = format!("measured-{count}-{sample}");
            let key = BatchKey::Named(label.clone());
            let request = ExecuteRequest {
                subject: clock.clone(),
                expected_revision: revision,
                operation: "touch".into(),
                arguments: json!({}),
                fulfillments: BTreeMap::new(),
                recording: recording(&label),
            };
            let (outcome, batch_time) = measured(|| {
                facade
                    .execute_batch(
                        context(&label),
                        key.clone(),
                        vec![BatchAction::Execute(request)],
                        CallWait::Forever,
                    )
                    .unwrap()
            });
            assert!(!outcome.replayed());
            revision += 1;
            let (history, history_time) = measured(|| {
                facade
                    .scoped()
                    .read_history(&clock, CallWait::Forever)
                    .unwrap()
            });
            assert_eq!(history.records.len() as u64, revision);
            let (lookup, lookup_time) = measured(|| {
                facade
                    .scoped()
                    .lookup_batch(&key, CallWait::Forever)
                    .unwrap()
                    .unwrap()
            });
            assert_eq!(lookup.records.len(), 1);
            let (snapshot, snapshot_time) =
                measured(|| facade.complete_snapshot(CallWait::Forever).unwrap());
            let terminal = snapshot
                .histories
                .iter()
                .find(|h| h.history.subject == clock)
                .unwrap();
            assert_eq!(terminal.terminal.revision, revision);
            println!(
                "sample events={count} round={sample} batch={batch_time:?} history={history_time:?} lookup={lookup_time:?} snapshot={snapshot_time:?}"
            );
            if sample > 0 {
                batches.push(batch_time);
                histories.push(history_time);
                lookups.push(lookup_time);
                snapshots.push(snapshot_time);
            }
        }
        let batch = median(&mut batches);
        println!(
            "median initial_events={count} open={open_elapsed:?} batch={batch:?} history={:?} lookup={:?} snapshot={:?}",
            median(&mut histories),
            median(&mut lookups),
            median(&mut snapshots)
        );
        batch_medians.push((count, batch));
        assert_eq!(
            facade.shutdown(ShutdownMode::Drain, CallWait::Forever),
            ShutdownOutcome::Joined { provider: Ok(()) }
        );
    }
    let small = batch_medians[0].1;
    for (count, median) in &batch_medians[1..] {
        assert!(
            *median <= small * 2,
            "shared-clock batch at {count} events costs {median:?}, more than twice 55-event {small:?}; all {batch_medians:?}"
        );
    }
}

/// Opens per size whose median is reported.
const OPENS: usize = 5;

/// The open-cost baseline a bounded recorded open is compared against.
///
/// For each seeded size it reports three medians of [`OPENS`] runs, in microseconds:
/// `start` is the consumer's whole open (worker thread, runtime, SQLite open, projector attach and
/// the store open), `capture` is the provider's complete tenant capture alone, and `verify` is the
/// store open on an already open provider: that capture plus the whole-model build. Every run
/// uses a provider handle opened for it, as a new process would, because a handle skips the
/// SHA-256 of blob content it has already verified. It also reports how many canonical record and
/// request bytes the verified model holds and the median time to parse every record's canonical
/// text: a floor under any open that loads a persisted whole model instead of verifying one. It
/// asserts what a `ProviderTracked` open does today, so a change that stops verifying the whole
/// store cannot pass as this baseline. Each `open-cost` line is the stable output the evidence
/// file records.
#[test]
#[ignore = "release performance probe; run explicitly on a quiet host"]
fn each_provider_tracked_open_verifies_the_whole_store_and_reports_its_median_cost() {
    assert!(!cfg!(debug_assertions), "this probe requires --release");
    let directory = tempfile::tempdir_in(env!("CARGO_TARGET_TMPDIR")).unwrap();
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();
    let registry = registry();
    for count in [55, 601, 1203] {
        let path = directory.path().join(format!("open-{count}.sqlite3"));
        let (authority, _) = runtime.block_on(seeded(&path, &registry, count));
        let tenant = TenantId::new(&authority.tenant).unwrap();
        let (mut starts, mut captures, mut verifies) = (Vec::new(), Vec::new(), Vec::new());
        for _ in 0..OPENS {
            let (mut facade, start_time) =
                measured(|| start_tracked(&path, &registry, authority.clone()));
            starts.push(start_time);
            assert_eq!(
                facade.shutdown(ShutdownMode::Drain, CallWait::Forever),
                ShutdownOutcome::Joined { provider: Ok(()) }
            );
            let backend = attached(&runtime, &path);
            let (capture, capture_time) = measured(|| {
                runtime
                    .block_on(backend.capture_tenant(&tenant, projection_specs(), LIMITS))
                    .unwrap()
            });
            assert_eq!(
                capture.events.len(),
                count,
                "the provider captured the tenant"
            );
            drop((capture, backend));
            captures.push(capture_time);
            let backend = attached(&runtime, &path);
            let (store, verify_time) = measured(|| {
                runtime
                    .block_on(EventlogRecordedStore::open_with_policy(
                        backend,
                        authority.clone(),
                        LIMITS,
                        CapturePolicy::ProviderTracked,
                    ))
                    .unwrap()
            });
            let calls = store.calls();
            assert_eq!(
                (calls.captures, calls.model_builds, calls.records_decoded),
                (1, 1, count - 1),
                "a ProviderTracked open is one complete capture and one whole-model build that \
                 decodes every recorded entry; a bounded open changes this baseline: {calls:?}"
            );
            drop(store);
            verifies.push(verify_time);
        }
        // What the verified model holds per record, as canonical text, and what parsing it costs.
        let mut facade = start_tracked(&path, &registry, authority);
        let snapshot = facade.complete_snapshot(CallWait::Forever).unwrap();
        assert_eq!(
            facade.shutdown(ShutdownMode::Drain, CallWait::Forever),
            ShutdownOutcome::Joined { provider: Ok(()) }
        );
        let records: Vec<_> = snapshot
            .histories
            .iter()
            .flat_map(|h| &h.history.records)
            .collect();
        assert_eq!(
            records.len(),
            count - 1,
            "every recorded entry is in the model"
        );
        let texts: Vec<_> = records
            .iter()
            .map(|r| {
                (
                    record_domain(&r.entry),
                    record_comparison_bytes(&r.entry).unwrap(),
                )
            })
            .collect();
        let record_bytes: usize = texts.iter().map(|(_, bytes)| bytes.len()).sum();
        let request_bytes: usize = records.iter().map(|r| r.request_bytes.len()).sum();
        let mut decodes = Vec::new();
        for _ in 0..OPENS {
            let ((), decode_time) = measured(|| {
                for (domain, bytes) in &texts {
                    std::hint::black_box(read_record_in_domain(domain, bytes).unwrap());
                }
            });
            decodes.push(decode_time);
        }
        let samples = format!(
            "start_us=[{}] capture_us=[{}] verify_us=[{}] record_parse_us=[{}]",
            micros(&starts),
            micros(&captures),
            micros(&verifies),
            micros(&decodes)
        );
        println!(
            "open-cost policy=ProviderTracked events={count} opens={OPENS} start_median_us={} capture_median_us={} verify_median_us={} model_record_bytes={record_bytes} model_request_bytes={request_bytes} record_parse_median_us={} {samples}",
            median(&mut starts).as_micros(),
            median(&mut captures).as_micros(),
            median(&mut verifies).as_micros(),
            median(&mut decodes).as_micros(),
        );
    }
}

/// One seeded group appended after the checkpoint: the clock touched and one new peer, two events,
/// written through a `FullVerification` facade, which never touches the open checkpoint.
fn append_group(path: &Path, registry: &Registry, authority: Authority, revision: u64) {
    let mut facade = RecordedProviderFacade::start(
        registry.clone(),
        EventlogRecordedStoreOwner::Sqlite {
            path: path.to_string_lossy().into_owned(),
            prefix: PREFIX.into(),
            authority,
            limits: LIMITS,
        },
        BridgeConfig {
            queue_capacity: NonZeroU16::new(8).unwrap(),
        },
    )
    .unwrap();
    facade
        .execute_batch(
            context("suffix"),
            BatchKey::Named("suffix".into()),
            vec![
                BatchAction::Execute(ExecuteRequest {
                    subject: Subject::new("metadata", "clock").unwrap(),
                    expected_revision: revision,
                    operation: "touch".into(),
                    arguments: json!({}),
                    fulfillments: BTreeMap::new(),
                    recording: recording("suffix-clock"),
                }),
                BatchAction::Create(CreateRequest {
                    subject: Subject::new("metadata", "suffix-peer").unwrap(),
                    definition_version: 1,
                    fields: json!({"title":"suffix-peer"}),
                    recording: recording("suffix-peer"),
                }),
            ],
            CallWait::Forever,
        )
        .unwrap();
    assert_eq!(
        facade.shutdown(ShutdownMode::Drain, CallWait::Forever),
        ShutdownOutcome::Joined { provider: Ok(()) }
    );
}

/// The open cost with a persisted checkpoint, against the baseline above (issue 55, acceptance 5).
///
/// Each seeded store gets durable open checkpoints enabled and one tracked open whose drain
/// persists a checkpoint at the head. Two treatments are then measured, [`OPENS`] opens each:
/// `checkpoint`, the checkpoint at the head the previous process left, which the provider answers
/// `Unchanged`; and `suffix`, one seeded-sized group (two events) appended after it by a
/// `FullVerification` writer, which the open verifies as a suffix. Every measured facade is shut
/// down with `CancelQueued`, which persists nothing, so each open of a treatment starts from the
/// same checkpoint. `start` is the consumer's whole open, as in the baseline; `verify` is the store
/// open on an already attached provider. The probe asserts how each open verified, that a
/// `FullVerification` open of the same store still verifies all of it, and the bound: the median
/// `start` at the largest store is at most twice the median at the smallest, for both treatments.
#[test]
#[ignore = "release performance probe; run explicitly on a quiet host"]
fn each_open_from_a_checkpoint_at_the_previous_head_stays_within_twice_the_smallest_store() {
    assert!(!cfg!(debug_assertions), "this probe requires --release");
    let directory = tempfile::tempdir_in(env!("CARGO_TARGET_TMPDIR")).unwrap();
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();
    let registry = registry();
    let mut medians: BTreeMap<&str, Vec<(usize, Duration)>> = BTreeMap::new();
    for count in [55, 601, 1203] {
        let path = directory.path().join(format!("checkpoint-{count}.sqlite3"));
        let (authority, groups) = runtime.block_on(seeded(&path, &registry, count));
        runtime.block_on(async {
            eventlog_sqlite::SqliteEventStore::open_existing(path.to_str().unwrap(), PREFIX)
                .await
                .unwrap()
                .enable_durable_continuity()
                .await
                .unwrap();
        });
        let mut writer = start_tracked(&path, &registry, authority.clone());
        assert_eq!(writer.open_verification(), OpenVerification::Complete);
        assert_eq!(
            writer.shutdown(ShutdownMode::Drain, CallWait::Forever),
            ShutdownOutcome::Joined { provider: Ok(()) }
        );
        let full = runtime
            .block_on(EventlogRecordedStore::open_with_policy(
                attached(&runtime, &path),
                authority.clone(),
                LIMITS,
                CapturePolicy::FullVerification,
            ))
            .unwrap();
        let calls = full.calls();
        assert_eq!(
            (calls.captures, calls.model_builds, calls.records_decoded),
            (1, 1, count - 1),
            "a FullVerification open beside the checkpoint verifies the whole store: {calls:?}"
        );
        drop(full);
        for (treatment, expected) in [
            ("checkpoint", OpenVerification::Checkpoint),
            ("suffix", OpenVerification::Suffix { events: 2 }),
        ] {
            if treatment == "suffix" {
                append_group(&path, &registry, authority.clone(), groups);
            }
            let (mut starts, mut verifies) = (Vec::new(), Vec::new());
            for _ in 0..OPENS {
                let (mut facade, start_time) =
                    measured(|| start_tracked(&path, &registry, authority.clone()));
                assert_eq!(facade.open_verification(), expected, "{treatment} {count}");
                assert_eq!(
                    facade.shutdown(ShutdownMode::CancelQueued, CallWait::Forever),
                    ShutdownOutcome::Joined { provider: Ok(()) }
                );
                starts.push(start_time);
                let backend = attached(&runtime, &path);
                let (store, verify_time) = measured(|| {
                    runtime
                        .block_on(EventlogRecordedStore::open_with_policy(
                            backend,
                            authority.clone(),
                            LIMITS,
                            CapturePolicy::ProviderTracked,
                        ))
                        .unwrap()
                });
                assert_eq!(store.open_verification(), expected, "{treatment} {count}");
                let calls = store.calls();
                assert_eq!(
                    (calls.captures, calls.model_builds),
                    (0, 0),
                    "a bounded open takes no capture and builds no model: {calls:?}"
                );
                drop(store);
                verifies.push(verify_time);
            }
            let samples = format!(
                "start_us=[{}] verify_us=[{}]",
                micros(&starts),
                micros(&verifies)
            );
            let start = median(&mut starts);
            println!(
                "open-cost policy=ProviderTracked treatment={treatment} events={count} opens={OPENS} start_median_us={} verify_median_us={} {samples}",
                start.as_micros(),
                median(&mut verifies).as_micros(),
            );
            medians.entry(treatment).or_default().push((count, start));
        }
    }
    for (treatment, sizes) in &medians {
        let small = sizes[0].1;
        for (count, median) in &sizes[1..] {
            assert!(
                *median <= small * 2,
                "{treatment}: the open at {count} events costs {median:?}, more than twice the 55-event {small:?}; all {sizes:?}"
            );
        }
    }
}
