//! Release probe for shared-batch closure growth on real SQLite authority.
//!
//! Run explicitly with `cargo +1.91.0 test --release -p entity-eventlog
//! --features sqlite,sync-bridge --test shared_clock_cost -- --ignored --nocapture`.
//! Seeding uses public kernel/canonical-byte/provider APIs and the real ER projector;
//! a complete cold open validates the fixture before any measurement.
#![cfg(all(feature = "sqlite", feature = "sync-bridge"))]

use entity_core::{Registry, Runtime};
use entity_eventlog::{
    AsyncBindingProvisioner, Authority, CapturePolicy, ErRecordedProjector,
    EventlogBindingProvisioner, EventlogOperationContext, EventlogRecordedStore,
    RecordedProviderFacade, projection_specs,
    sync::{BridgeConfig, CallWait, EventlogRecordedStoreOwner, ShutdownMode, ShutdownOutcome},
};
use entity_executor::{BatchAction, ExecuteRequest};
use entity_store::{
    Expect, RecordedCommit, Recording,
    asynchronous::{
        AppendMember, AsyncRecordedReader, BatchKey, RecordedEntry, Subject,
        batch_comparison_bytes, canonical_domain_bytes, original_request_comparison_bytes,
        record_comparison_bytes,
    },
};
use eventlog_core::{
    AppendGroup, AtomicEventStore, CaptureLimits, CommandMeta, ConsistentTenantCapture, EventStore,
    Expected, InlineProjectionAdmin, NewEvent, NoGuard, StreamAppend, StreamId, TenantId,
};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    num::NonZeroU16,
    path::Path,
    sync::Arc,
    time::{Duration, Instant},
};
use time::OffsetDateTime;

const PREFIX: &str = "shared_clock_cost";
const LIMITS: CaptureLimits = CaptureLimits {
    max_events: 10_000,
    max_blobs: 40_000,
    max_projection_rows: 40_000,
    max_payload_bytes: 512 * 1024 * 1024,
};

fn registry() -> Registry {
    let mut fields = serde_json::Map::new();
    fields.insert("title".into(), json!({"type":"string", "required":true}));
    for index in 0..96 {
        fields.insert(
            format!("metadata_field_{index:04}_carrying_a_long_declared_name"),
            json!({"type":"string", "max_length":64}),
        );
    }
    let mut registry = Registry::new();
    registry
        .register(
            serde_json::from_value(json!({
                "entity":"metadata", "version":1, "schema":{"fields":fields},
                "lifecycle":{"initial":"open", "states":["open"]},
                "operations":{"touch":{"transitions":[{"from":"open", "to":"open"}], "emits":[]}}
            }))
            .unwrap(),
        )
        .unwrap();
    registry
}

fn recording(id: &str) -> Recording {
    Recording {
        record_id: id.into(),
        recorded_at: "2026-10-03T00:00:00Z".into(),
        correlation: None,
        causation: None,
        actor: None,
    }
}
fn context(id: &str) -> EventlogOperationContext {
    EventlogOperationContext {
        subject: "cost-probe".into(),
        actor: "entity-eventlog-test".into(),
        request_id: format!("request-{id}"),
        trace_id: format!("trace-{id}"),
        causation_id: None,
        causation_depth: 0,
        occurred_at: OffsetDateTime::UNIX_EPOCH,
    }
}
fn framed(domain: &str, bytes: &[u8]) -> String {
    let mut hash = Sha256::new();
    hash.update(domain.as_bytes());
    hash.update([0]);
    hash.update((bytes.len() as u64).to_be_bytes());
    hash.update(bytes);
    format!("sha256:{:x}", hash.finalize())
}
fn key(domain: &str, value: Value) -> String {
    let wrapped = canonical_domain_bytes("_", value).unwrap();
    framed(domain, &wrapped[5..wrapped.len() - 1])
}

// Fixture wire envelopes intentionally live only in this test. Real projector and cold ER
// verification must accept every generated byte; measured operations use no fixture shortcut.
async fn seed_group(
    backend: &eventlog_sqlite::SqliteEventStore,
    authority: &Authority,
    index: usize,
    members: Vec<AppendMember>,
) {
    let batch_key = BatchKey::Named(format!("seed-{index}"));
    let batch_wire = json!(["named", format!("seed-{index}")]);
    let batch_bytes = batch_comparison_bytes(&batch_key, &members).unwrap();
    let batch_digest = framed("er.eventlog.batch-blob-key/1", &batch_bytes);
    let mut blobs = vec![(batch_digest.clone(), batch_bytes)];
    let tenant = TenantId::new(&authority.tenant).unwrap();
    let mut appends = Vec::new();
    for (member_index, member) in members.iter().enumerate() {
        let subject = member.entry.subject();
        let record_bytes = record_comparison_bytes(&member.entry).unwrap();
        let record_digest = framed("er.eventlog.record-blob-key/1", &record_bytes);
        let request_digest = framed("er.eventlog.request-blob-key/1", &member.request_bytes);
        let wrapper = canonical_domain_bytes(
            "er.eventlog.recorded-entry/1",
            json!({
                "authority":authority, "batch_blob":batch_digest, "batch_key":batch_wire,
                "member_index":member_index, "record_blob":record_digest,
                "request_blob":request_digest, "subject":[subject.entity, subject.id],
            }),
        )
        .unwrap();
        let wrapper_digest = framed("er.eventlog.recorded-entry-blob-key/1", &wrapper);
        blobs.extend([
            (record_digest, record_bytes),
            (request_digest, member.request_bytes.clone()),
            (wrapper_digest.clone(), wrapper),
        ]);
        let stream_key = key(
            "er.eventlog.subject-stream-key/1",
            json!({"authority":authority, "subject":[subject.entity, subject.id]}),
        );
        appends.push(StreamAppend {
            stream: StreamId::new(tenant.clone(), "er.subject", stream_key).unwrap(),
            expected: match member.expect {
                Expect::Absent => Expected::NoStream,
                Expect::Revision(revision) => Expected::Exact(revision),
            },
            events: vec![
                NewEvent::new("er.recorded_entry", 1, json!({"blob":wrapper_digest})).unwrap(),
            ],
        });
    }
    let ctx = context(&format!("seed-{index}"));
    let group = AppendGroup {
        tenant,
        appends,
        meta: CommandMeta {
            idempotency_key: key(
                "er.eventlog.batch-command-key/1",
                json!({"authority":authority,"batch_key":batch_wire}),
            ),
            request_hash: batch_digest,
            subject: ctx.subject,
            actor: ctx.actor,
            request_id: ctx.request_id,
            trace_id: ctx.trace_id,
            causation_id: None,
            causation_depth: 0,
            occurred_at: ctx.occurred_at,
            claim: None,
        },
    };
    let result = backend
        .append_group_guarded_with_blobs(&group, Arc::new(NoGuard), &blobs)
        .await
        .expect("fixture group/projector commits");
    assert!(!result.deduplicated);
    assert_eq!(result.appends.len(), 2);
}

async fn seeded(path: &Path, registry: &Registry, total_events: usize) -> (Authority, u64) {
    assert_eq!(total_events % 2, 1);
    let backend = Arc::new(
        eventlog_sqlite::SqliteEventStore::open(path.to_str().unwrap(), PREFIX)
            .await
            .unwrap(),
    );
    let tenant = TenantId::new("shared-clock").unwrap();
    let authority = Authority {
        logical_scope: "shared-clock-scope".into(),
        tenant: tenant.as_str().into(),
        stream_identity: backend.stream_identity(&tenant).await.unwrap(),
    };
    let projector = Arc::new(ErRecordedProjector::new());
    backend.create_projections(projector.clone()).await.unwrap();
    backend.attach_inline_existing(projector).await.unwrap();
    EventlogBindingProvisioner::new(backend.clone(), LIMITS)
        .provision_binding(authority.clone(), context("binding"))
        .await
        .unwrap();
    let runtime = Runtime::new(registry);
    let mut clock = None;
    let groups = (total_events - 1) / 2;
    for index in 0..groups {
        let decision = match clock.as_ref() {
            None => runtime.create("metadata", 1, "clock", json!({"title":"clock"})),
            Some(instance) => runtime.execute(instance, "touch", json!({})),
        }
        .unwrap();
        let expected = clock
            .as_ref()
            .map_or(Expect::Absent, |state: &entity_core::EntityInstance| {
                Expect::Revision(state.revision)
            });
        clock = Some(decision.instance.clone());
        let clock_entry = RecordedEntry::Decision(
            RecordedCommit::new(decision, &recording(&format!("clock-{index}"))).unwrap(),
        );
        let peer_id = format!("peer-{index}");
        let peer_entry = RecordedEntry::Decision(
            RecordedCommit::new(
                runtime
                    .create("metadata", 1, &peer_id, json!({"title":peer_id}))
                    .unwrap(),
                &recording(&format!("peer-{index}")),
            )
            .unwrap(),
        );
        let members = [(clock_entry, expected), (peer_entry, Expect::Absent)]
            .into_iter()
            .map(|(entry, expect)| {
                let bytes = original_request_comparison_bytes(&entry).unwrap();
                AppendMember::new(expect, entry, bytes)
            })
            .collect();
        seed_group(&backend, &authority, index, members).await;
    }
    let capture = backend
        .capture_tenant(&tenant, projection_specs(), LIMITS)
        .await
        .unwrap();
    assert_eq!(
        capture.events.len(),
        total_events,
        "includes one authority-binding event"
    );
    println!(
        "seed events={total_events} recorded_entries={} groups={groups} blob_bytes={}",
        total_events - 1,
        capture
            .blobs
            .iter()
            .map(|blob| blob.bytes.len())
            .sum::<usize>()
    );
    drop(capture);
    let verified = EventlogRecordedStore::open_with_policy(
        backend,
        authority.clone(),
        LIMITS,
        CapturePolicy::ProviderTracked,
    )
    .await
    .expect("cold ER verification validates all fixture bytes and histories");
    let snapshot = verified
        .complete_snapshot(&authority.logical_scope)
        .await
        .unwrap();
    assert_eq!(
        snapshot
            .histories
            .iter()
            .map(|h| h.history.records.len())
            .sum::<usize>(),
        total_events - 1
    );
    assert_eq!(snapshot.histories.len(), groups + 1);
    let before = verified.calls();
    let start = Instant::now();
    let unchanged = verified
        .complete_snapshot(&authority.logical_scope)
        .await
        .unwrap();
    let unchanged_time = start.elapsed();
    assert_eq!(unchanged, snapshot);
    assert_eq!(before.captures, 1, "cold open remains fully verified");
    assert_eq!(
        verified.calls(),
        before,
        "unchanged capture does no new verification work"
    );
    println!(
        "unchanged events={total_events} elapsed={unchanged_time:?} calls_before={before:?} calls_after={:?}",
        verified.calls()
    );
    (authority, groups as u64)
}

fn median(samples: &mut [Duration]) -> Duration {
    samples.sort();
    samples[samples.len() / 2]
}
fn measured<T>(f: impl FnOnce() -> T) -> (T, Duration) {
    let start = Instant::now();
    let output = f();
    (output, start.elapsed())
}

#[test]
#[ignore = "release performance probe; run explicitly on a quiet host"]
fn warm_shared_clock_batches_remain_within_twice_small_store_cost() {
    assert!(!cfg!(debug_assertions), "this probe requires --release");
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target/issue-51-scratch/perf");
    std::fs::create_dir_all(&root).unwrap();
    let directory = tempfile::tempdir_in(root).unwrap();
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();
    let registry = registry();
    let mut batch_medians = Vec::new();
    for count in [55, 601, 1203] {
        let path = directory.path().join(format!("events-{count}.sqlite3"));
        let seed_start = Instant::now();
        let (authority, mut revision) = runtime.block_on(seeded(&path, &registry, count));
        println!(
            "seed_and_verify events={count} elapsed={:?}",
            seed_start.elapsed()
        );
        let (mut facade, open_elapsed) = measured(|| {
            RecordedProviderFacade::start_with_read_policy(
                registry.clone(),
                EventlogRecordedStoreOwner::Sqlite {
                    path: path.to_string_lossy().into_owned(),
                    prefix: PREFIX.into(),
                    authority,
                    limits: LIMITS,
                },
                BridgeConfig {
                    queue_capacity: NonZeroU16::new(8).unwrap(),
                },
                CapturePolicy::ProviderTracked,
            )
            .unwrap()
        });
        let clock = Subject::new("metadata", "clock").unwrap();
        let mut batches = Vec::new();
        let mut histories = Vec::new();
        let mut lookups = Vec::new();
        let mut snapshots = Vec::new();
        for sample in 0..6 {
            let label = format!("measured-{count}-{sample}");
            let key = BatchKey::Named(label.clone());
            let request = ExecuteRequest {
                subject: clock.clone(),
                expected_revision: revision,
                operation: "touch".into(),
                arguments: json!({}),
                fulfillments: BTreeMap::new(),
                recording: recording(&label),
            };
            let (outcome, batch_time) = measured(|| {
                facade
                    .execute_batch(
                        context(&label),
                        key.clone(),
                        vec![BatchAction::Execute(request)],
                        CallWait::Forever,
                    )
                    .unwrap()
            });
            assert!(!outcome.replayed());
            revision += 1;
            let (history, history_time) = measured(|| {
                facade
                    .scoped()
                    .read_history(&clock, CallWait::Forever)
                    .unwrap()
            });
            assert_eq!(history.records.len() as u64, revision);
            let (lookup, lookup_time) = measured(|| {
                facade
                    .scoped()
                    .lookup_batch(&key, CallWait::Forever)
                    .unwrap()
                    .unwrap()
            });
            assert_eq!(lookup.records.len(), 1);
            let (snapshot, snapshot_time) =
                measured(|| facade.complete_snapshot(CallWait::Forever).unwrap());
            let terminal = snapshot
                .histories
                .iter()
                .find(|h| h.history.subject == clock)
                .unwrap();
            assert_eq!(terminal.terminal.revision, revision);
            println!(
                "sample events={count} round={sample} batch={batch_time:?} history={history_time:?} lookup={lookup_time:?} snapshot={snapshot_time:?}"
            );
            if sample > 0 {
                batches.push(batch_time);
                histories.push(history_time);
                lookups.push(lookup_time);
                snapshots.push(snapshot_time);
            }
        }
        let batch = median(&mut batches);
        println!(
            "median initial_events={count} open={open_elapsed:?} batch={batch:?} history={:?} lookup={:?} snapshot={:?}",
            median(&mut histories),
            median(&mut lookups),
            median(&mut snapshots)
        );
        batch_medians.push((count, batch));
        assert_eq!(
            facade.shutdown(ShutdownMode::Drain, CallWait::Forever),
            ShutdownOutcome::Joined { provider: Ok(()) }
        );
    }
    let small = batch_medians[0].1;
    for (count, median) in &batch_medians[1..] {
        assert!(
            *median <= small * 2,
            "shared-clock batch at {count} events costs {median:?}, more than twice 55-event {small:?}; all {batch_medians:?}"
        );
    }
}
